-- ============================================================
-- Migration 0055 — per-tenant report key (replaces the REPORTS_SECRET Worker secret)
-- The Bot Crew · Agent Platform
--
-- 0054 gated GET /reports/info-gaps/:tenantId behind a Worker secret, which meant a
-- `wrangler secret put` before the first report could be opened — one more manual
-- step, and one key for every client. This moves the key into the tenant row:
-- generated by the migration for existing tenants and by the default for new ones,
-- unique per tenant, rotated with an UPDATE. A client can be handed its own URL
-- without exposing anyone else's report.
--
-- ROLLBACK: additive (a new NOT NULL column with a volatile default — Postgres
-- evaluates it per existing row, so every tenant gets a distinct key). The deployed
-- Worker ignores the column until the version that reads it ships.
-- ============================================================

ALTER TABLE public.tenant_config
  ADD COLUMN IF NOT EXISTS report_key text NOT NULL DEFAULT encode(gen_random_bytes(16), 'hex');
COMMENT ON COLUMN public.tenant_config.report_key IS
  'Per-tenant key for GET /reports/info-gaps/:tenantId?key=… (0055). Rotate with an UPDATE; never NULL.';

CREATE UNIQUE INDEX IF NOT EXISTS idx_tenant_config_report_key ON public.tenant_config (report_key);
